#!/usr/bin/env node
/**
 * Validates canonical JSON data files against schemas in data/schemas/.
 */
import { readFileSync, readdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import Ajv from "ajv";
import addFormats from "ajv-formats";
import yaml from "yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const ajv = new Ajv({ allErrors: true, strict: false });
addFormats(ajv);

const jsonValidations = [
  {
    data: "data/ict-spend-baseline.json",
    schema: "data/schemas/ict-spend-baseline.schema.json",
  },
];

let failed = false;

for (const { data, schema } of jsonValidations) {
  const schemaObj = JSON.parse(readFileSync(join(root, schema), "utf8"));
  const validate = ajv.compile(schemaObj);
  const dataObj = JSON.parse(readFileSync(join(root, data), "utf8"));
  if (!validate(dataObj)) {
    console.error(`FAIL ${data}:`, validate.errors);
    failed = true;
  } else {
    console.log(`OK   ${data}`);
  }
}

const secondaryDir = join(root, "data/secondary-sources");
const secondarySchema = JSON.parse(
  readFileSync(join(root, "data/schemas/secondary-source.schema.json"), "utf8")
);
const validateSecondary = ajv.compile(secondarySchema);

for (const file of readdirSync(secondaryDir).filter((f) => f.endsWith(".yaml"))) {
  const content = yaml.parse(readFileSync(join(secondaryDir, file), "utf8"));
  if (!validateSecondary(content)) {
    console.error(`FAIL data/secondary-sources/${file}:`, validateSecondary.errors);
    failed = true;
  } else {
    console.log(`OK   data/secondary-sources/${file}`);
  }
}

const academicPath = join(root, "data/academic-literature/wp15-core-references.yaml");
if (readFileSync(academicPath, "utf8")) {
  const academicSchema = JSON.parse(
    readFileSync(join(root, "data/schemas/academic-literature.schema.json"), "utf8")
  );
  const validateAcademic = ajv.compile(academicSchema);
  const academicContent = yaml.parse(readFileSync(academicPath, "utf8"));
  if (!validateAcademic(academicContent)) {
    console.error("FAIL data/academic-literature/wp15-core-references.yaml:", validateAcademic.errors);
    failed = true;
  } else {
    console.log("OK   data/academic-literature/wp15-core-references.yaml");
  }
}

// TAP synthesis (object) — generated by orchestrate-synthesis.mjs; skip if not yet generated.
const tapSynthPath = join(root, "data/tap-synthesis.json");
if (existsSync(tapSynthPath)) {
  const tapSchema = JSON.parse(
    readFileSync(join(root, "data/schemas/tap-synthesis.schema.json"), "utf8")
  );
  const validateTap = ajv.compile(tapSchema);
  const tapObj = JSON.parse(readFileSync(tapSynthPath, "utf8"));
  if (!validateTap(tapObj)) {
    console.error("FAIL data/tap-synthesis.json:", validateTap.errors);
    failed = true;
  } else {
    console.log("OK   data/tap-synthesis.json");
  }
}

// Claim ledger (JSONL) — validate one object per non-empty line.
const ledgerPath = join(root, "data/claim-ledger.jsonl");
if (existsSync(ledgerPath)) {
  const ledgerSchema = JSON.parse(
    readFileSync(join(root, "data/schemas/claim-ledger.schema.json"), "utf8")
  );
  const validateLedger = ajv.compile(ledgerSchema);
  const lines = readFileSync(ledgerPath, "utf8").split("\n").filter((l) => l.trim());
  let lineNo = 0;
  let ledgerOk = true;
  for (const line of lines) {
    lineNo += 1;
    if (!validateLedger(JSON.parse(line))) {
      console.error(`FAIL data/claim-ledger.jsonl line ${lineNo}:`, validateLedger.errors);
      failed = true;
      ledgerOk = false;
    }
  }
  if (ledgerOk) console.log(`OK   data/claim-ledger.jsonl (${lines.length} lines)`);
}

process.exit(failed ? 1 : 0);
